controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7

    command_interfaces: ['position']
    state_interfaces: ['position', 'velocity']

    state_publish_rate: 25.0
    action_monitor_rate: 20.0

    gains:
        joint1: {p: 100.0, d: 0.1}
        joint2: {p: 100.0, d: 0.1}
        joint3: {p: 100.0, d: 0.1}
        joint4: {p: 100.0, d: 0.1}
        joint5: {p: 100.0, d: 0.1}
        joint6: {p: 100.0, d: 0.1}
        joint7: {p: 100.0, d: 0.1}